CREATE TABLE `BPP`.`ATTRIBUTE_SCOPES` (
  `ATS_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Attribute Scope ID',
  `ATS_ATTR_NAME` VARCHAR(50) NOT NULL COMMENT 'Attribute name',
  `ATS_RANGE_FROM` DOUBLE COMMENT 'Range from',
  `ATS_RANGE_TO` DOUBLE COMMENT 'Range to', 
  PRIMARY KEY (`ATS_ID`)
);

CREATE TABLE `BPP`.`LITERALS` (
  `LIT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Literal ID',
  `LIT_DESCRIPTION` VARCHAR(50) NOT NULL COMMENT 'Literal description',
  `LIT_IS_NEGATIVE` BOOLEAN NOT NULL DEFAULT 0 COMMENT 'Is Literal negated',
  `LIT_ATS_ID` INT NOT NULL COMMENT 'Attribute Scope ID',
  INDEX `LIT_ATS_ID_idx` (`LIT_ATS_ID` ASC),
  CONSTRAINT `FK_LIT_ATS_ID`
    FOREIGN KEY (`LIT_ATS_ID`)
    REFERENCES `bpp`.`attribute_scopes` (`ATS_ID`),
  PRIMARY KEY (`LIT_ID`)
);

CREATE TABLE `BPP`.`CLAUSES` (
  `CLA_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Clause ID',
  `CLA_TYPE` VARCHAR(1) NOT NULL DEFAULT 'S' COMMENT 'Clause type: S - Standard, B - Business',
  PRIMARY KEY (`CLA_ID`)
);

CREATE TABLE `BPP`.`CLAUSE_LITERAL` (
  `CLA_ID` INT NOT NULL,
  `LIT_ID` INT NOT NULL,
  INDEX `CLA_ID_idx` (`CLA_ID` ASC),
  INDEX `LIT_ID_idx` (`LIT_ID` ASC),
  CONSTRAINT `CLA_LIT_ID`
    FOREIGN KEY (`CLA_ID`)
    REFERENCES `bpp`.`clauses` (`CLA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LIT_CLA_ID`
    FOREIGN KEY (`LIT_ID`)
    REFERENCES `bpp`.`literals` (`LIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);