CREATE TABLE `BPP`.`FORMULAS` (
  `FOR_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Formula ID',
  `FOR_TYPE` VARCHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Formula type: A - Assessment, B - Bankrupt (Test), N - Not bankrupt (Test)',
  PRIMARY KEY (`FOR_ID`)
);

CREATE TABLE `BPP`.`FORMULA_CLAUSE` (
  `FOR_ID` INT NOT NULL,
  `CLA_ID` INT NOT NULL,
  INDEX `FOR_ID_idx` (`FOR_ID` ASC),
  INDEX `CLA_ID_idx` (`CLA_ID` ASC),
  CONSTRAINT `FOR_CLA_ID`
    FOREIGN KEY (`FOR_ID`)
    REFERENCES `bpp`.`formulas` (`FOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CLA_FOR_ID`
    FOREIGN KEY (`CLA_ID`)
    REFERENCES `bpp`.`clauses` (`CLA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);